import type { User, Club, ClubMembership, Expense, DirectorReport, CadetRosterItem, PendingExemption, DesligadoItem } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_diretor_fernando',
    username: 'diretor.fernando',
    email: 'fernando@fab.mil.br',
    name: 'Fernando Santos (Cadete Intendente)',
    warName: 'FERNANDO',
    cadetNumber: '23/001',
    squadron: 'Athos - Diretoria de Cédula',
    role: 'diretor',
    cpf: '999.888.777-66'
  },
  {
    id: 'usr_cadete_moro',
    username: 'cadete.moro',
    email: 'lucas.moro.bof@gmail.com',
    name: 'Lucas Moro Bof',
    warName: 'MORO',
    cadetNumber: '23/001',
    squadron: 'Athos',
    role: 'cadete',
    cpf: '173.367.937-54',
    phone: '27992774117'
  },
  {
    id: 'usr_cadete_resende',
    username: 'cadete.resende',
    email: 'renatoalmeidaresende@gmail.com',
    name: 'Renato Almeida Resende',
    warName: 'RESENDE',
    cadetNumber: '23/002',
    squadron: 'Athos',
    role: 'cadete',
    cpf: '955.102.561-00',
    phone: '32999474548'
  },
  {
    id: 'usr_cadete_kalil',
    username: 'cadete.kalil',
    email: 'kalil.santos2003@gmail.com',
    name: 'Kalil Lopes dos Santos',
    warName: 'KALIL',
    cadetNumber: '23/003',
    squadron: 'Athos',
    role: 'cadete',
    cpf: '125.525.494-70',
    phone: '84988034938'
  },
  {
    id: 'usr_scaer_geraes',
    username: 'gestor.geraes',
    email: 'geraes@scaer.mil.br',
    name: 'Capitão Aviador Mendes',
    warName: 'CAP. MENDES',
    cadetNumber: 'OF-087',
    squadron: 'Corpo de Instrutores',
    role: 'scaer',
    clubId: 'clb_geraes',
    cpf: '456.789.012-33'
  },
  {
    id: 'usr_scaer_musculacao',
    username: 'gestor.musculacao',
    email: 'musculacao@scaer.mil.br',
    name: 'Tenente Rocha',
    warName: 'TEN. ROCHA',
    cadetNumber: 'OF-112',
    squadron: 'Corpo de Instrutores',
    role: 'scaer',
    clubId: 'clb_musculacao',
    cpf: '567.890.123-44'
  }
];

export const INITIAL_CLUBS: Club[] = [
  {
    id: 'clb_geraes',
    name: 'GERAES',
    code: 'GERAES',
    description: 'Grêmio de Estudos Relações Aeronáuticas e Espaciais.',
    icon: 'Sparkles',
    monthlyFee: 20.00,
    category: 'Cultura',
    status: 'active',
    managerId: 'usr_scaer_geraes',
    managerName: 'CAP. MENDES',
    memberCount: 42,
  },
  {
    id: 'clb_investimento',
    name: 'INVESTIMENTO',
    code: 'INV',
    description: 'Clube de Mercado Financeiro e Investimentos.',
    icon: 'Crown',
    monthlyFee: 5.00,
    category: 'Cultura',
    status: 'active',
    managerId: 'usr_scaer_geraes',
    managerName: 'CAP. MENDES',
    memberCount: 35,
  },
  {
    id: 'clb_literatura',
    name: 'LITERATURA',
    code: 'LIT',
    description: 'Clube do Livro, Leitura e Debates Literários.',
    icon: 'Sparkles',
    monthlyFee: 10.00,
    category: 'Cultura',
    status: 'active',
    managerId: 'usr_scaer_geraes',
    managerName: 'CAP. MENDES',
    memberCount: 18,
  },
  {
    id: 'clb_musculacao',
    name: 'MUSCULAÇÃO',
    code: 'MUSC',
    description: 'Acompanhamento físico e musculação acadêmica.',
    icon: 'Target',
    monthlyFee: 20.00,
    category: 'Esporte',
    status: 'active',
    managerId: 'usr_scaer_musculacao',
    managerName: 'TEN. ROCHA',
    memberCount: 88,
  },
  {
    id: 'clb_ctnn',
    name: 'CTNN',
    code: 'CTNN',
    description: 'Clube de Tiro e Caça de Nuporanga / Náutica.',
    icon: 'Target',
    monthlyFee: 15.00,
    category: 'Esporte',
    status: 'active',
    managerId: 'usr_scaer_musculacao',
    managerName: 'TEN. ROCHA',
    memberCount: 29,
  },
  {
    id: 'clb_escalada',
    name: 'ESCALADA',
    code: 'ESC',
    description: 'Escalada esportiva e montanhismo.',
    icon: 'Target',
    monthlyFee: 15.00,
    category: 'Esporte',
    status: 'active',
    managerId: 'usr_scaer_musculacao',
    managerName: 'TEN. ROCHA',
    memberCount: 22,
  },
  {
    id: 'clb_csav',
    name: 'CSAV',
    code: 'CSAV',
    description: 'Clube de Saúde, Socorro e Aviação.',
    icon: 'Plane',
    monthlyFee: 20.00,
    category: 'Militar',
    status: 'active',
    managerId: 'usr_scaer_geraes',
    managerName: 'CAP. MENDES',
    memberCount: 50,
  },
  {
    id: 'clb_jiujitsu',
    name: 'JIU-JITSU',
    code: 'BJJ',
    description: 'Treinamento e prática de Jiu-Jitsu.',
    icon: 'Target',
    monthlyFee: 10.00,
    category: 'Esporte',
    status: 'active',
    managerId: 'usr_scaer_musculacao',
    managerName: 'TEN. ROCHA',
    memberCount: 40,
  },
  {
    id: 'clb_musica',
    name: 'MÚSICA',
    code: 'MUS',
    description: 'Prática de instrumentos e coral da SCAER.',
    icon: 'Sparkles',
    monthlyFee: 10.00,
    category: 'Cultura',
    status: 'active',
    managerId: 'usr_scaer_geraes',
    managerName: 'CAP. MENDES',
    memberCount: 30,
  },
  {
    id: 'clb_ctg',
    name: 'CTG',
    code: 'CTG',
    description: 'Centro de Tradicões Gaúchas.',
    icon: 'Crown',
    monthlyFee: 15.00,
    category: 'Social',
    status: 'active',
    managerId: 'usr_scaer_geraes',
    managerName: 'CAP. MENDES',
    memberCount: 25,
  },
  {
    id: 'clb_cocafa',
    name: 'COCAFA',
    code: 'COCAFA',
    description: 'Comissão de Organização Cultural e Esportiva.',
    icon: 'Sparkles',
    monthlyFee: 10.00,
    category: 'Social',
    status: 'active',
    managerId: 'usr_scaer_geraes',
    managerName: 'CAP. MENDES',
    memberCount: 60,
  },
  {
    id: 'clb_neag',
    name: 'NEAG',
    code: 'NEAG',
    description: 'Núcleo de Estudos de Geopolítica e Estratégia.',
    icon: 'Cpu',
    monthlyFee: 10.00,
    category: 'Tecnologia',
    status: 'active',
    managerId: 'usr_scaer_geraes',
    managerName: 'CAP. MENDES',
    memberCount: 15,
  },
  {
    id: 'clb_negec',
    name: 'NEGEC',
    code: 'NEGEC',
    description: 'Núcleo de Estudos da Guerra Eletrônica e Cibernética.',
    icon: 'Cpu',
    monthlyFee: 7.00,
    category: 'Tecnologia',
    status: 'active',
    managerId: 'usr_scaer_geraes',
    managerName: 'CAP. MENDES',
    memberCount: 20,
  },
  {
    id: 'clb_airsoft',
    name: 'AIRSOFT',
    code: 'AIR',
    description: 'Treinamento tático e partidas de Airsoft.',
    icon: 'Target',
    monthlyFee: 10.00,
    category: 'Militar',
    status: 'active',
    managerId: 'usr_scaer_musculacao',
    managerName: 'TEN. ROCHA',
    memberCount: 38,
  }
];

export const INITIAL_MEMBERSHIPS: ClubMembership[] = [
  {
    id: 'mem_1',
    userId: 'usr_cadete_moro',
    userName: 'MORO',
    cadetNumber: '23/001',
    squadron: 'Athos',
    clubId: 'clb_geraes',
    clubName: 'GERAES',
    status: 'approved',
    requestedAt: '2026-01-15'
  },
  {
    id: 'mem_2',
    userId: 'usr_cadete_moro',
    userName: 'MORO',
    cadetNumber: '23/001',
    squadron: 'Athos',
    clubId: 'clb_musculacao',
    clubName: 'MUSCULAÇÃO',
    status: 'approved',
    requestedAt: '2026-02-01'
  },
  {
    id: 'mem_3',
    userId: 'usr_cadete_resende',
    userName: 'RESENDE',
    cadetNumber: '23/002',
    squadron: 'Athos',
    clubId: 'clb_musculacao',
    clubName: 'MUSCULAÇÃO',
    status: 'approved',
    requestedAt: '2026-03-10'
  },
  {
    id: 'mem_4',
    userId: 'usr_cadete_kalil',
    userName: 'KALIL',
    cadetNumber: '23/003',
    squadron: 'Athos',
    clubId: 'clb_investimento',
    clubName: 'INVESTIMENTO',
    status: 'approved',
    requestedAt: '2026-04-05'
  }
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp_101',
    userId: 'usr_cadete_moro',
    userName: 'MORO',
    cadetNumber: '23/001',
    clubId: 'clb_geraes',
    clubName: 'GERAES',
    description: 'MENSALIDADE GERAES',
    amount: 20.00,
    category: 'Mensalidade',
    billingPeriod: '2026-07',
    launchType: 'recurring',
    createdBy: 'usr_scaer_geraes',
    createdByName: 'CAP. MENDES',
    createdAt: '2026-07-01 08:00:00',
    status: 'pending'
  },
  {
    id: 'exp_102',
    userId: 'usr_cadete_moro',
    userName: 'MORO',
    cadetNumber: '23/001',
    clubId: 'clb_musculacao',
    clubName: 'MUSCULAÇÃO',
    description: 'MENSALIDADE MUSCULAÇÃO',
    amount: 20.00,
    category: 'Mensalidade',
    billingPeriod: '2026-07',
    launchType: 'recurring',
    createdBy: 'usr_scaer_musculacao',
    createdByName: 'TEN. ROCHA',
    createdAt: '2026-07-01 08:00:00',
    status: 'pending'
  },
  {
    id: 'exp_103',
    userId: 'usr_cadete_resende',
    userName: 'RESENDE',
    cadetNumber: '23/002',
    clubId: 'clb_musculacao',
    clubName: 'MUSCULAÇÃO',
    description: 'MENSALIDADE MUSCULAÇÃO',
    amount: 20.00,
    category: 'Mensalidade',
    billingPeriod: '2026-07',
    launchType: 'recurring',
    createdBy: 'usr_scaer_musculacao',
    createdByName: 'TEN. ROCHA',
    createdAt: '2026-07-01 08:00:00',
    status: 'pending'
  },
  {
    id: 'exp_104',
    userId: 'usr_cadete_kalil',
    userName: 'KALIL',
    cadetNumber: '23/003',
    clubId: 'clb_investimento',
    clubName: 'INVESTIMENTO',
    description: 'MENSALIDADE INVESTIMENTO',
    amount: 5.00,
    category: 'Mensalidade',
    billingPeriod: '2026-07',
    launchType: 'recurring',
    createdBy: 'usr_scaer_geraes',
    createdByName: 'CAP. MENDES',
    createdAt: '2026-07-01 08:00:00',
    status: 'pending'
  }
];

export const INITIAL_REPORTS: DirectorReport[] = [
  {
    id: 'rep_2026_06',
    title: 'Relatório Consolidado SCAER - Junho/2026',
    period: '2026-06',
    reportType: 'synthetic',
    totalAmount: 12450.00,
    totalLaunches: 112,
    totalCadets: 185,
    verificationHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    issuedAt: '2026-07-01 10:00:00',
    issuedBy: 'usr_diretor_fernando',
    directorName: '23/001 FERNANDO'
  }
];

// Efetivo de Amostra extraído da planilha CédulAthos 2k26 (BANCO DE DADOS)
export const INITIAL_ROSTER: CadetRosterItem[] = [
  { id: 'r_1', number: '23/001', warName: 'MORO', fullName: 'Lucas Moro Bof', squadron: 'Athos', cpf: '173.367.937-54', phone: '27992774117', email: 'lucas.moro.bof@gmail.com' },
  { id: 'r_2', number: '23/002', warName: 'RESENDE', fullName: 'Renato Almeida Resende', squadron: 'Athos', cpf: '955.102.561-00', phone: '32999474548', email: 'renatoalmeidaresende@gmail.com' },
  { id: 'r_3', number: '23/003', warName: 'KALIL', fullName: 'Kalil Lopes dos Santos', squadron: 'Athos', cpf: '125.525.494-70', phone: '84988034938', email: 'kalil.santos2003@gmail.com' },
  { id: 'r_4', number: '23/005', warName: 'MAGAN', fullName: 'Maria Eduarda Magan Dal Monte', squadron: 'Athos', cpf: '484.353.458-74', phone: '11987473758', email: 'dudasangster@gmail.com' },
  { id: 'r_5', number: '23/006', warName: 'HERNANDES', fullName: 'João Victor Engel Hernandes', squadron: 'Athos', cpf: '702.572.716-43', phone: '35997355830', email: 'jveh21@gmail.com' }
];

// Pendências e Isenções da Planilha (PENDÊNCIAS)
export const INITIAL_EXEMPTIONS: PendingExemption[] = [
  { id: 'p_1', cadetName: 'CAIO MIRANDA', description: 'NÃO COBRAR GERAES NO MÊS DE JULHO', period: '2026-07', status: 'active' },
  { id: 'p_2', cadetName: 'SARDEIRO', description: 'NÃO COBRAR CTG NO MÊS DE JULHO e AGOSTO', period: '2026-07', status: 'active' }
];

// Cadetes Desligados da Planilha (Desligados)
export const INITIAL_DESLIGADOS: DesligadoItem[] = [
  { id: 'd_1', period: '2026-08', cadetNumber: '24/283', warName: 'MATTOS', amount: 23.00, clubName: 'SCAER', description: 'JOGO DA COPA 24/06' },
  { id: 'd_2', period: '2026-08', cadetNumber: '25/092', warName: 'DAVI', amount: 13.00, clubName: 'SCAER', description: 'JOGO DA COPA 29/06' }
];
